/**
 * AutoWunsch — Statischer PKW-Modellkatalog.
 *
 * GENERIERT — nicht manuell bearbeiten.
 * Quelle: https://www.pkw.de/api/v1/brands/models?with_main_ce=true
 * Erzeugt von: scripts/fetch-pkw-models.ts
 *
 * 1456 Modelle aus 115 Marken.
 */

export interface PkwModel {
  id: number;
  make: string;
  name: string;
}

export const PKW_MODELS: readonly PkwModel[] = [
  { id: 2774, make: "Abarth", name: "124 Spider" },
  { id: 1719, make: "Abarth", name: "500" },
  { id: 1720, make: "Abarth", name: "500C" },
  { id: 1813, make: "Abarth", name: "595" },
  { id: 3177, make: "Abarth", name: "595 Competizione" },
  { id: 3178, make: "Abarth", name: "595 Turismo" },
  { id: 1814, make: "Abarth", name: "595C" },
  { id: 1815, make: "Abarth", name: "695" },
  { id: 1818, make: "Abarth", name: "andere" },
  { id: 1651, make: "Aixam", name: "andere" },
  { id: 1647, make: "Aixam", name: "City" },
  { id: 1648, make: "Aixam", name: "Crossline" },
  { id: 2389, make: "Aixam", name: "Crossover" },
  { id: 1650, make: "Aixam", name: "Scouty R" },
  { id: 1, make: "Alfa Romeo", name: "145" },
  { id: 13, make: "Alfa Romeo", name: "146" },
  { id: 2, make: "Alfa Romeo", name: "147" },
  { id: 11, make: "Alfa Romeo", name: "155" },
  { id: 3, make: "Alfa Romeo", name: "156" },
  { id: 4, make: "Alfa Romeo", name: "159" },
  { id: 12, make: "Alfa Romeo", name: "164" },
  { id: 5, make: "Alfa Romeo", name: "166" },
  { id: 14, make: "Alfa Romeo", name: "33" },
  { id: 1776, make: "Alfa Romeo", name: "4C" },
  { id: 1156, make: "Alfa Romeo", name: "75" },
  { id: 1152, make: "Alfa Romeo", name: "8C" },
  { id: 16, make: "Alfa Romeo", name: "andere" },
  { id: 15, make: "Alfa Romeo", name: "Brera" },
  { id: 18, make: "Alfa Romeo", name: "Giulia" },
  { id: 1153, make: "Alfa Romeo", name: "Giulietta" },
  { id: 7, make: "Alfa Romeo", name: "GT" },
  { id: 8, make: "Alfa Romeo", name: "GTV" },
  { id: 1652, make: "Alfa Romeo", name: "Junior" },
  { id: 1158, make: "Alfa Romeo", name: "MiTo" },
  { id: 10, make: "Alfa Romeo", name: "Spider" },
  { id: 1155, make: "Alfa Romeo", name: "Sprint" },
  { id: 2959, make: "Alfa Romeo", name: "Stelvio" },
  { id: 3487, make: "Alfa Romeo", name: "Tonale" },
  { id: 23, make: "Alpina", name: "andere" },
  { id: 20, make: "Alpina", name: "B10" },
  { id: 21, make: "Alpina", name: "B3" },
  { id: 2582, make: "Alpina", name: "B4" },
  { id: 1039, make: "Alpina", name: "B5" },
  { id: 1161, make: "Alpina", name: "B6" },
  { id: 1045, make: "Alpina", name: "B7" },
  { id: 22, make: "Alpina", name: "D10" },
  { id: 1160, make: "Alpina", name: "D3" },
  { id: 2677, make: "Alpina", name: "D4" },
  { id: 1820, make: "Alpina", name: "D5" },
  { id: 1163, make: "Alpina", name: "Roadster S" },
  { id: 3428, make: "Alpina", name: "XB7" },
  { id: 1821, make: "Alpina", name: "XD3" },
  { id: 3345, make: "Alpina", name: "XD4" },
  { id: 3605, make: "Alpine", name: "andere" },
  { id: 24, make: "andere", name: "andere" },
  { id: 1568, make: "Artega", name: "GT" },
  { id: 25, make: "ASIA Motors", name: "Rocsta" },
  { id: 1756, make: "Aston Martin", name: "Cygnet" },
  { id: 1164, make: "Aston Martin", name: "DB" },
  { id: 3191, make: "Aston Martin", name: "DB11" },
  { id: 27, make: "Aston Martin", name: "DB7" },
  { id: 28, make: "Aston Martin", name: "DB9" },
  { id: 1165, make: "Aston Martin", name: "DBS" },
  { id: 1605, make: "Aston Martin", name: "Rapide" },
  { id: 1653, make: "Aston Martin", name: "V12 Vantage" },
  { id: 1050, make: "Aston Martin", name: "V8" },
  { id: 30, make: "Aston Martin", name: "V8 Vantage" },
  { id: 29, make: "Aston Martin", name: "Vanquish" },
  { id: 1169, make: "Aston Martin", name: "Vantage" },
  { id: 1166, make: "Aston Martin", name: "Virage" },
  { id: 47, make: "Audi", name: "100" },
  { id: 49, make: "Audi", name: "200" },
  { id: 48, make: "Audi", name: "80" },
  { id: 52, make: "Audi", name: "90" },
  { id: 1556, make: "Audi", name: "A1" },
  { id: 33, make: "Audi", name: "A2" },
  { id: 34, make: "Audi", name: "A3" },
  { id: 35, make: "Audi", name: "A4" },
  { id: 2498, make: "Audi", name: "A4 allroad quattro" },
  { id: 992, make: "Audi", name: "A5" },
  { id: 36, make: "Audi", name: "A6" },
  { id: 2495, make: "Audi", name: "A6 allroad quattro" },
  { id: 1630, make: "Audi", name: "A7" },
  { id: 37, make: "Audi", name: "A8" },
  { id: 53, make: "Audi", name: "andere" },
  { id: 39, make: "Audi", name: "Cabriolet" },
  { id: 50, make: "Audi", name: "Coupe" },
  { id: 3200, make: "Audi", name: "e-tron" },
  { id: 2688, make: "Audi", name: "Q2" },
  { id: 1758, make: "Audi", name: "Q3" },
  { id: 3346, make: "Audi", name: "Q4" },
  { id: 1084, make: "Audi", name: "Q5" },
  { id: 40, make: "Audi", name: "Q7" },
  { id: 3113, make: "Audi", name: "Q8" },
  { id: 1172, make: "Audi", name: "QUATTRO" },
  { id: 993, make: "Audi", name: "R8" },
  { id: 1824, make: "Audi", name: "RS 3" },
  { id: 1016, make: "Audi", name: "RS 4" },
  { id: 1658, make: "Audi", name: "RS 5" },
  { id: 1017, make: "Audi", name: "RS 6" },
  { id: 1826, make: "Audi", name: "RS 7" },
  { id: 1827, make: "Audi", name: "RSQ3" },
  { id: 3268, make: "Audi", name: "RSQ8" },
  { id: 2164, make: "Audi", name: "S1" },
  { id: 42, make: "Audi", name: "S3" },
  { id: 43, make: "Audi", name: "S4" },
  { id: 994, make: "Audi", name: "S5" },
  { id: 44, make: "Audi", name: "S6" },
  { id: 1828, make: "Audi", name: "S7" },
  { id: 45, make: "Audi", name: "S8" },
  { id: 3114, make: "Audi", name: "SQ2" },
  { id: 1829, make: "Audi", name: "SQ5" },
  { id: 2772, make: "Audi", name: "SQ7" },
  { id: 3266, make: "Audi", name: "SQ8" },
  { id: 46, make: "Audi", name: "TT" },
  { id: 51, make: "Audi", name: "V8" },
  { id: 60, make: "Austin", name: "andere" },
  { id: 59, make: "Austin", name: "Estate" },
  { id: 58, make: "Austin", name: "Maestro" },
  { id: 56, make: "Austin", name: "Metro" },
  { id: 55, make: "Austin", name: "Montego" },
  { id: 1661, make: "Austin Healey", name: "andere" },
  { id: 2199, make: "Austin Healey", name: "Sprite" },
  { id: 3102, make: "Baic", name: "andere" },
  { id: 3087, make: "Baic", name: "B40" },
  { id: 3347, make: "Baic", name: "BJ20" },
  { id: 3099, make: "Baic", name: "D20" },
  { id: 3086, make: "Baic", name: "Senova X35" },
  { id: 3093, make: "Baic", name: "X25" },
  { id: 3096, make: "Baic", name: "X55" },
  { id: 3097, make: "Baic", name: "X65" },
  { id: 63, make: "Bentley", name: "andere" },
  { id: 1011, make: "Bentley", name: "Arnage" },
  { id: 61, make: "Bentley", name: "Azure" },
  { id: 2777, make: "Bentley", name: "Bentayga" },
  { id: 1012, make: "Bentley", name: "Brooklands" },
  { id: 62, make: "Bentley", name: "Continental" },
  { id: 1830, make: "Bentley", name: "Continental Flying Spur" },
  { id: 1831, make: "Bentley", name: "Continental GT" },
  { id: 1832, make: "Bentley", name: "Continental GTC" },
  { id: 1833, make: "Bentley", name: "Continental Supersports" },
  { id: 1834, make: "Bentley", name: "Flying Spur" },
  { id: 1174, make: "Bentley", name: "Mulsanne" },
  { id: 970, make: "BMW", name: "1er Reihe" },
  { id: 105, make: "BMW", name: "2002" },
  { id: 1793, make: "BMW", name: "2er Reihe" },
  { id: 969, make: "BMW", name: "3er Reihe" },
  { id: 1779, make: "BMW", name: "4er Reihe" },
  { id: 971, make: "BMW", name: "5er Reihe" },
  { id: 972, make: "BMW", name: "6er Reihe" },
  { id: 973, make: "BMW", name: "7er Reihe" },
  { id: 102, make: "BMW", name: "840" },
  { id: 101, make: "BMW", name: "850" },
  { id: 110, make: "BMW", name: "andere" },
  { id: 1786, make: "BMW", name: "i3" },
  { id: 3350, make: "BMW", name: "i4" },
  { id: 3545, make: "BMW", name: "i5" },
  { id: 3488, make: "BMW", name: "i7" },
  { id: 1787, make: "BMW", name: "i8" },
  { id: 3351, make: "BMW", name: "iX" },
  { id: 3352, make: "BMW", name: "iX3" },
  { id: 3267, make: "BMW", name: "M8" },
  { id: 3117, make: "BMW", name: "M850" },
  { id: 3034, make: "BMW", name: "X-Reihe" },
  { id: 2769, make: "BMW", name: "Z-Reihe" },
  { id: 1851, make: "Borgward", name: "andere" },
  { id: 1586, make: "Brilliance", name: "BS4" },
  { id: 1490, make: "Brilliance", name: "BS6" },
  { id: 119, make: "Buick", name: "Riviera" },
  { id: 3534, make: "BYD", name: "andere" },
  { id: 3546, make: "BYD", name: "ATTO 3" },
  { id: 3549, make: "BYD", name: "DOLPHIN" },
  { id: 3550, make: "BYD", name: "HAN" },
  { id: 3551, make: "BYD", name: "SEAL" },
  { id: 3552, make: "BYD", name: "TANG" },
  { id: 1184, make: "Cadillac", name: "Allante" },
  { id: 131, make: "Cadillac", name: "andere" },
  { id: 1806, make: "Cadillac", name: "ATS" },
  { id: 126, make: "Cadillac", name: "BLS" },
  { id: 2682, make: "Cadillac", name: "CT6" },
  { id: 130, make: "Cadillac", name: "CTS" },
  { id: 125, make: "Cadillac", name: "Deville" },
  { id: 129, make: "Cadillac", name: "Eldorado" },
  { id: 123, make: "Cadillac", name: "Escalade" },
  { id: 124, make: "Cadillac", name: "Seville" },
  { id: 133, make: "Cadillac", name: "SRX" },
  { id: 132, make: "Cadillac", name: "STS" },
  { id: 127, make: "Cadillac", name: "XLR" },
  { id: 3354, make: "Cadillac", name: "XT4" },
  { id: 2780, make: "Cadillac", name: "XT5" },
  { id: 2380, make: "Caterham", name: "Roadsport" },
  { id: 2374, make: "Caterham", name: "Seven 165" },
  { id: 3570, make: "Cenntro", name: "andere" },
  { id: 1761, make: "Changhe", name: "Freedom" },
  { id: 157, make: "Chevrolet", name: "Alero" },
  { id: 158, make: "Chevrolet", name: "andere" },
  { id: 1185, make: "Chevrolet", name: "Astro" },
  { id: 155, make: "Chevrolet", name: "Aveo" },
  { id: 134, make: "Chevrolet", name: "Blazer" },
  { id: 2591, make: "Chevrolet", name: "C-Serie" },
  { id: 152, make: "Chevrolet", name: "Camaro" },
  { id: 1188, make: "Chevrolet", name: "Caprice" },
  { id: 150, make: "Chevrolet", name: "Captiva" },
  { id: 1189, make: "Chevrolet", name: "Chevelle" },
  { id: 135, make: "Chevrolet", name: "Corvette" },
  { id: 1580, make: "Chevrolet", name: "Cruze" },
  { id: 1192, make: "Chevrolet", name: "El Camino" },
  { id: 151, make: "Chevrolet", name: "Epica" },
  { id: 136, make: "Chevrolet", name: "Evanda" },
  { id: 1085, make: "Chevrolet", name: "HHR" },
  { id: 1195, make: "Chevrolet", name: "Impala" },
  { id: 138, make: "Chevrolet", name: "Kalos" },
  { id: 139, make: "Chevrolet", name: "Lacetti" },
  { id: 1757, make: "Chevrolet", name: "Malibu" },
  { id: 141, make: "Chevrolet", name: "Matiz" },
  { id: 142, make: "Chevrolet", name: "Nubira" },
  { id: 1723, make: "Chevrolet", name: "Orlando" },
  { id: 143, make: "Chevrolet", name: "Rezzo" },
  { id: 144, make: "Chevrolet", name: "Silverado" },
  { id: 1612, make: "Chevrolet", name: "Spark" },
  { id: 1201, make: "Chevrolet", name: "Suburban" },
  { id: 154, make: "Chevrolet", name: "Tahoe" },
  { id: 146, make: "Chevrolet", name: "Trailblazer" },
  { id: 147, make: "Chevrolet", name: "Trans Sport" },
  { id: 2484, make: "Chevrolet", name: "Trax" },
  { id: 1857, make: "Chevrolet", name: "Volt" },
  { id: 162, make: "Chrysler", name: "300C" },
  { id: 175, make: "Chrysler", name: "300M" },
  { id: 176, make: "Chrysler", name: "andere" },
  { id: 163, make: "Chrysler", name: "Crossfire" },
  { id: 1202, make: "Chrysler", name: "Daytona" },
  { id: 1673, make: "Chrysler", name: "ES" },
  { id: 164, make: "Chrysler", name: "Grand Voyager" },
  { id: 1674, make: "Chrysler", name: "Imperial" },
  { id: 171, make: "Chrysler", name: "Le Baron" },
  { id: 165, make: "Chrysler", name: "Neon" },
  { id: 1205, make: "Chrysler", name: "New Yorker" },
  { id: 174, make: "Chrysler", name: "Pacifica" },
  { id: 166, make: "Chrysler", name: "PT Cruiser" },
  { id: 1206, make: "Chrysler", name: "Saratoga" },
  { id: 167, make: "Chrysler", name: "Sebring" },
  { id: 168, make: "Chrysler", name: "Stratus" },
  { id: 169, make: "Chrysler", name: "Viper" },
  { id: 173, make: "Chrysler", name: "Vision" },
  { id: 170, make: "Chrysler", name: "Voyager" },
  { id: 195, make: "Citroen", name: "2CV" },
  { id: 198, make: "Citroen", name: "andere" },
  { id: 193, make: "Citroen", name: "AX" },
  { id: 177, make: "Citroen", name: "Berlingo" },
  { id: 1208, make: "Citroen", name: "BX" },
  { id: 1008, make: "Citroen", name: "C-Crosser" },
  { id: 2786, make: "Citroen", name: "C-Elysée" },
  { id: 1858, make: "Citroen", name: "C-Zero" },
  { id: 178, make: "Citroen", name: "C1" },
  { id: 179, make: "Citroen", name: "C2" },
  { id: 180, make: "Citroen", name: "C3" },
  { id: 3197, make: "Citroen", name: "C3 Aircross" },
  { id: 1685, make: "Citroen", name: "C3 Picasso" },
  { id: 181, make: "Citroen", name: "C4" },
  { id: 1749, make: "Citroen", name: "C4 Aircross" },
  { id: 2135, make: "Citroen", name: "C4 Cactus" },
  { id: 1684, make: "Citroen", name: "C4 Picasso" },
  { id: 3198, make: "Citroen", name: "C4 SpaceTourer" },
  { id: 182, make: "Citroen", name: "C5" },
  { id: 3110, make: "Citroen", name: "C5 Aircross" },
  { id: 197, make: "Citroen", name: "C6" },
  { id: 183, make: "Citroen", name: "C8" },
  { id: 196, make: "Citroen", name: "CX" },
  { id: 1209, make: "Citroen", name: "DS" },
  { id: 1677, make: "Citroen", name: "DS 3" },
  { id: 1678, make: "Citroen", name: "DS 4" },
  { id: 1729, make: "Citroen", name: "DS 5" },
  { id: 3199, make: "Citroen", name: "DS4 Crossback" },
  { id: 184, make: "Citroen", name: "Evasion" },
  { id: 1686, make: "Citroen", name: "Grand C4 Picasso" },
  { id: 1210, make: "Citroen", name: "GSA" },
  { id: 185, make: "Citroen", name: "Jumper" },
  { id: 186, make: "Citroen", name: "Jumpy" },
  { id: 2988, make: "Citroen", name: "Méhari" },
  { id: 1086, make: "Citroen", name: "Nemo" },
  { id: 188, make: "Citroen", name: "Saxo" },
  { id: 1211, make: "Citroen", name: "SM" },
  { id: 2789, make: "Citroen", name: "SpaceTourer" },
  { id: 189, make: "Citroen", name: "Xantia" },
  { id: 194, make: "Citroen", name: "XM" },
  { id: 190, make: "Citroen", name: "Xsara" },
  { id: 191, make: "Citroen", name: "Xsara Picasso" },
  { id: 192, make: "Citroen", name: "ZX" },
  { id: 1860, make: "Corvette", name: "C2" },
  { id: 1075, make: "Corvette", name: "C3" },
  { id: 1076, make: "Corvette", name: "C4" },
  { id: 201, make: "Corvette", name: "C5" },
  { id: 1861, make: "Corvette", name: "C7" },
  { id: 3356, make: "Corvette", name: "C8" },
  { id: 202, make: "Corvette", name: "Convertible" },
  { id: 204, make: "Corvette", name: "Coupe" },
  { id: 206, make: "Corvette", name: "Z06" },
  { id: 3252, make: "Cupra", name: "andere" },
  { id: 3251, make: "Cupra", name: "Ateca" },
  { id: 3431, make: "Cupra", name: "Born" },
  { id: 3276, make: "Cupra", name: "Formentor" },
  { id: 3359, make: "Cupra", name: "Leon" },
  { id: 3572, make: "Cupra", name: "Tavascan" },
  { id: 209, make: "Dacia", name: "andere" },
  { id: 1771, make: "Dacia", name: "Dokker" },
  { id: 1614, make: "Dacia", name: "Duster" },
  { id: 3432, make: "Dacia", name: "Jogger" },
  { id: 1747, make: "Dacia", name: "Lodgy" },
  { id: 207, make: "Dacia", name: "Logan" },
  { id: 1862, make: "Dacia", name: "Logan Pick-Up" },
  { id: 1213, make: "Dacia", name: "Sandero" },
  { id: 2168, make: "Dacia", name: "Sandero Stepway" },
  { id: 3360, make: "Dacia", name: "Spring" },
  { id: 218, make: "Daewoo", name: "Espero" },
  { id: 210, make: "Daewoo", name: "Evanda" },
  { id: 211, make: "Daewoo", name: "Kalos" },
  { id: 1216, make: "Daewoo", name: "Korando" },
  { id: 212, make: "Daewoo", name: "Lacetti" },
  { id: 213, make: "Daewoo", name: "Lanos" },
  { id: 217, make: "Daewoo", name: "Leganza" },
  { id: 214, make: "Daewoo", name: "Matiz" },
  { id: 219, make: "Daewoo", name: "Nexia" },
  { id: 215, make: "Daewoo", name: "Nubira" },
  { id: 216, make: "Daewoo", name: "Rezzo" },
  { id: 2418, make: "DAF", name: "andere" },
  { id: 229, make: "Daihatsu", name: "Applause" },
  { id: 233, make: "Daihatsu", name: "Charade" },
  { id: 221, make: "Daihatsu", name: "Copen" },
  { id: 222, make: "Daihatsu", name: "Cuore" },
  { id: 230, make: "Daihatsu", name: "Feroza" },
  { id: 228, make: "Daihatsu", name: "Gran Move" },
  { id: 231, make: "Daihatsu", name: "Hijet" },
  { id: 1014, make: "Daihatsu", name: "Materia" },
  { id: 1095, make: "Daihatsu", name: "Move" },
  { id: 1221, make: "Daihatsu", name: "Rocky" },
  { id: 223, make: "Daihatsu", name: "Sirion" },
  { id: 224, make: "Daihatsu", name: "Terios" },
  { id: 226, make: "Daihatsu", name: "Trevis" },
  { id: 225, make: "Daihatsu", name: "YRV" },
  { id: 1865, make: "De Tomaso", name: "andere" },
  { id: 3050, make: "DFM", name: "andere" },
  { id: 3277, make: "DFSK", name: "andere" },
  { id: 3361, make: "DFSK", name: "Fengon" },
  { id: 3362, make: "DFSK", name: "Glory" },
  { id: 3363, make: "DFSK", name: "Seres 3" },
  { id: 241, make: "Dodge", name: "andere" },
  { id: 1015, make: "Dodge", name: "Avenger" },
  { id: 238, make: "Dodge", name: "Caliber" },
  { id: 1548, make: "Dodge", name: "Challenger" },
  { id: 1546, make: "Dodge", name: "Charger" },
  { id: 1224, make: "Dodge", name: "Durango" },
  { id: 242, make: "Dodge", name: "Grand Caravan" },
  { id: 1225, make: "Dodge", name: "Journey" },
  { id: 1003, make: "Dodge", name: "Nitro" },
  { id: 240, make: "Dodge", name: "RAM" },
  { id: 237, make: "Dodge", name: "Viper" },
  { id: 2792, make: "Donkervoort", name: "D8" },
  { id: 3056, make: "DS Automobiles", name: "andere" },
  { id: 2799, make: "DS Automobiles", name: "DS3" },
  { id: 2801, make: "DS Automobiles", name: "DS4" },
  { id: 2804, make: "DS Automobiles", name: "DS4 Crossback" },
  { id: 3103, make: "DS Automobiles", name: "DS7" },
  { id: 3364, make: "DS Automobiles", name: "DS9" },
  { id: 3579, make: "e.GO", name: "Life" },
  { id: 1231, make: "Ferrari", name: "250" },
  { id: 3365, make: "Ferrari", name: "296 GTB" },
  { id: 255, make: "Ferrari", name: "308" },
  { id: 1235, make: "Ferrari", name: "348" },
  { id: 246, make: "Ferrari", name: "360" },
  { id: 247, make: "Ferrari", name: "456" },
  { id: 1868, make: "Ferrari", name: "458" },
  { id: 1607, make: "Ferrari", name: "458 Italia" },
  { id: 3366, make: "Ferrari", name: "488 Pista" },
  { id: 2810, make: "Ferrari", name: "488 Spider" },
  { id: 256, make: "Ferrari", name: "512" },
  { id: 248, make: "Ferrari", name: "575" },
  { id: 1869, make: "Ferrari", name: "599 GTB" },
  { id: 3203, make: "Ferrari", name: "599 GTO" },
  { id: 249, make: "Ferrari", name: "612" },
  { id: 3123, make: "Ferrari", name: "812" },
  { id: 259, make: "Ferrari", name: "andere" },
  { id: 1606, make: "Ferrari", name: "California" },
  { id: 1241, make: "Ferrari", name: "Daytona" },
  { id: 250, make: "Ferrari", name: "F355" },
  { id: 252, make: "Ferrari", name: "F430" },
  { id: 257, make: "Ferrari", name: "F550" },
  { id: 3367, make: "Ferrari", name: "F8" },
  { id: 1873, make: "Ferrari", name: "FF" },
  { id: 3124, make: "Ferrari", name: "GTC4Lusso" },
  { id: 3081, make: "Ferrari", name: "Portofino" },
  { id: 3491, make: "Ferrari", name: "Purosangue" },
  { id: 3368, make: "Ferrari", name: "Roma" },
  { id: 3369, make: "Ferrari", name: "SF90" },
  { id: 1244, make: "Ferrari", name: "Superamerica" },
  { id: 1875, make: "Fiat", name: "124" },
  { id: 282, make: "Fiat", name: "126" },
  { id: 1245, make: "Fiat", name: "127" },
  { id: 1247, make: "Fiat", name: "131" },
  { id: 283, make: "Fiat", name: "500" },
  { id: 1876, make: "Fiat", name: "500C" },
  { id: 1877, make: "Fiat", name: "500L" },
  { id: 3205, make: "Fiat", name: "500L Cross" },
  { id: 1878, make: "Fiat", name: "500L Living" },
  { id: 1879, make: "Fiat", name: "500L Trekking" },
  { id: 3206, make: "Fiat", name: "500L Urban" },
  { id: 3207, make: "Fiat", name: "500L Wagon" },
  { id: 2275, make: "Fiat", name: "500X" },
  { id: 287, make: "Fiat", name: "600" },
  { id: 288, make: "Fiat", name: "andere" },
  { id: 260, make: "Fiat", name: "Barchetta" },
  { id: 261, make: "Fiat", name: "Brava" },
  { id: 262, make: "Fiat", name: "Bravo" },
  { id: 290, make: "Fiat", name: "Cinquecento" },
  { id: 280, make: "Fiat", name: "Coupe" },
  { id: 263, make: "Fiat", name: "Croma" },
  { id: 264, make: "Fiat", name: "Doblo" },
  { id: 265, make: "Fiat", name: "Ducato" },
  { id: 284, make: "Fiat", name: "Fiorino" },
  { id: 1763, make: "Fiat", name: "Freemont" },
  { id: 2813, make: "Fiat", name: "Fullback" },
  { id: 997, make: "Fiat", name: "Grande Punto" },
  { id: 266, make: "Fiat", name: "Idea" },
  { id: 1005, make: "Fiat", name: "Linea" },
  { id: 267, make: "Fiat", name: "Marea" },
  { id: 268, make: "Fiat", name: "Multipla" },
  { id: 3209, make: "Fiat", name: "New Panda" },
  { id: 269, make: "Fiat", name: "Palio" },
  { id: 270, make: "Fiat", name: "Panda" },
  { id: 271, make: "Fiat", name: "Panda 4x4" },
  { id: 2350, make: "Fiat", name: "Panda Cross" },
  { id: 272, make: "Fiat", name: "Punto" },
  { id: 1880, make: "Fiat", name: "Punto Evo" },
  { id: 1588, make: "Fiat", name: "Qubo" },
  { id: 1250, make: "Fiat", name: "Regata" },
  { id: 1251, make: "Fiat", name: "Ritmo" },
  { id: 273, make: "Fiat", name: "Scudo" },
  { id: 289, make: "Fiat", name: "Sedici" },
  { id: 274, make: "Fiat", name: "Seicento" },
  { id: 1253, make: "Fiat", name: "Spider Europa" },
  { id: 275, make: "Fiat", name: "Stilo" },
  { id: 286, make: "Fiat", name: "Strada" },
  { id: 2817, make: "Fiat", name: "Talento" },
  { id: 279, make: "Fiat", name: "Tipo" },
  { id: 277, make: "Fiat", name: "Ulysse" },
  { id: 281, make: "Fiat", name: "Uno" },
  { id: 1252, make: "Fiat", name: "X 1/9" },
  { id: 1759, make: "Fisker", name: "Karma" },
  { id: 3547, make: "Fisker", name: "Ocean" },
  { id: 325, make: "Ford", name: "andere" },
  { id: 1750, make: "Ford", name: "B-MAX" },
  { id: 314, make: "Ford", name: "Bronco" },
  { id: 297, make: "Ford", name: "C-Max" },
  { id: 326, make: "Ford", name: "Capri" },
  { id: 292, make: "Ford", name: "Cougar" },
  { id: 1256, make: "Ford", name: "Econovan" },
  { id: 1791, make: "Ford", name: "EcoSport" },
  { id: 1882, make: "Ford", name: "Edge" },
  { id: 293, make: "Ford", name: "Escort" },
  { id: 294, make: "Ford", name: "Explorer" },
  { id: 1259, make: "Ford", name: "Express" },
  { id: 2516, make: "Ford", name: "F-100" },
  { id: 316, make: "Ford", name: "F-150" },
  { id: 1261, make: "Ford", name: "F-350" },
  { id: 295, make: "Ford", name: "Fiesta" },
  { id: 296, make: "Ford", name: "Focus" },
  { id: 298, make: "Ford", name: "Fusion" },
  { id: 299, make: "Ford", name: "Galaxy" },
  { id: 3210, make: "Ford", name: "Grand C-Max" },
  { id: 3211, make: "Ford", name: "Grand Tourneo" },
  { id: 321, make: "Ford", name: "GT" },
  { id: 300, make: "Ford", name: "Ka" },
  { id: 3212, make: "Ford", name: "Ka/Ka+" },
  { id: 1073, make: "Ford", name: "Kuga" },
  { id: 301, make: "Ford", name: "Maverick" },
  { id: 302, make: "Ford", name: "Mondeo" },
  { id: 303, make: "Ford", name: "Mustang" },
  { id: 312, make: "Ford", name: "Orion" },
  { id: 291, make: "Ford", name: "Probe" },
  { id: 304, make: "Ford", name: "Puma" },
  { id: 305, make: "Ford", name: "Ranger" },
  { id: 2822, make: "Ford", name: "Raptor" },
  { id: 320, make: "Ford", name: "S-Max" },
  { id: 315, make: "Ford", name: "Scorpio" },
  { id: 322, make: "Ford", name: "Sierra" },
  { id: 306, make: "Ford", name: "Streetka" },
  { id: 311, make: "Ford", name: "Taunus" },
  { id: 307, make: "Ford", name: "Thunderbird" },
  { id: 308, make: "Ford", name: "Tourneo" },
  { id: 309, make: "Ford", name: "Transit" },
  { id: 310, make: "Ford", name: "Windstar" },
  { id: 2368, make: "GAC Gonow", name: "Way" },
  { id: 3450, make: "Genesis", name: "andere" },
  { id: 3446, make: "Genesis", name: "G70" },
  { id: 3447, make: "Genesis", name: "G80" },
  { id: 3553, make: "Genesis", name: "G90" },
  { id: 3448, make: "Genesis", name: "GV70" },
  { id: 3449, make: "Genesis", name: "GV80" },
  { id: 1888, make: "GMC", name: "Sierra" },
  { id: 1510, make: "GMC", name: "Yukon" },
  { id: 3603, make: "GWM", name: "andere" },
  { id: 3582, make: "GWM", name: "ORA 03" },
  { id: 3583, make: "GWM", name: "ORA 07" },
  { id: 3580, make: "GWM", name: "Wey 03" },
  { id: 3581, make: "GWM", name: "Wey 05" },
  { id: 329, make: "Honda", name: "Accord" },
  { id: 342, make: "Honda", name: "andere" },
  { id: 330, make: "Honda", name: "Civic" },
  { id: 343, make: "Honda", name: "Concerto" },
  { id: 331, make: "Honda", name: "CR-V" },
  { id: 1632, make: "Honda", name: "CR-Z" },
  { id: 341, make: "Honda", name: "CRX" },
  { id: 3370, make: "Honda", name: "e" },
  { id: 332, make: "Honda", name: "FR-V" },
  { id: 333, make: "Honda", name: "HR-V" },
  { id: 1264, make: "Honda", name: "Insight" },
  { id: 1265, make: "Honda", name: "Integra" },
  { id: 334, make: "Honda", name: "Jazz" },
  { id: 335, make: "Honda", name: "Legend" },
  { id: 336, make: "Honda", name: "Logo" },
  { id: 344, make: "Honda", name: "NSX" },
  { id: 340, make: "Honda", name: "Prelude" },
  { id: 337, make: "Honda", name: "S 2000" },
  { id: 338, make: "Honda", name: "Shuttle" },
  { id: 339, make: "Honda", name: "Stream" },
  { id: 1267, make: "Hummer", name: "H1" },
  { id: 346, make: "Hummer", name: "H2" },
  { id: 345, make: "Hummer", name: "H3" },
  { id: 348, make: "Hyundai", name: "Accent" },
  { id: 369, make: "Hyundai", name: "andere" },
  { id: 349, make: "Hyundai", name: "Atos" },
  { id: 3312, make: "Hyundai", name: "Bayon" },
  { id: 350, make: "Hyundai", name: "Coupe" },
  { id: 351, make: "Hyundai", name: "Elantra" },
  { id: 1582, make: "Hyundai", name: "Genesis" },
  { id: 353, make: "Hyundai", name: "Getz" },
  { id: 1895, make: "Hyundai", name: "Grand Santa Fe" },
  { id: 354, make: "Hyundai", name: "Grandeur" },
  { id: 355, make: "Hyundai", name: "H-1" },
  { id: 356, make: "Hyundai", name: "H-1 Starex" },
  { id: 1269, make: "Hyundai", name: "H100" },
  { id: 1270, make: "Hyundai", name: "H200" },
  { id: 2266, make: "Hyundai", name: "H350" },
  { id: 1089, make: "Hyundai", name: "i10" },
  { id: 1307, make: "Hyundai", name: "i20" },
  { id: 1004, make: "Hyundai", name: "i30" },
  { id: 1309, make: "Hyundai", name: "i40" },
  { id: 2703, make: "Hyundai", name: "IONIQ" },
  { id: 3313, make: "Hyundai", name: "IONIQ 5" },
  { id: 1896, make: "Hyundai", name: "ix 20" },
  { id: 1598, make: "Hyundai", name: "ix 35" },
  { id: 1306, make: "Hyundai", name: "ix55" },
  { id: 3082, make: "Hyundai", name: "Kona" },
  { id: 367, make: "Hyundai", name: "Lantra" },
  { id: 357, make: "Hyundai", name: "Matrix" },
  { id: 3213, make: "Hyundai", name: "Nexo" },
  { id: 368, make: "Hyundai", name: "Pony" },
  { id: 358, make: "Hyundai", name: "S-Coupe" },
  { id: 359, make: "Hyundai", name: "Santa Fe" },
  { id: 361, make: "Hyundai", name: "Sonata" },
  { id: 3314, make: "Hyundai", name: "STARIA" },
  { id: 362, make: "Hyundai", name: "Terracan" },
  { id: 363, make: "Hyundai", name: "Trajet" },
  { id: 364, make: "Hyundai", name: "Tucson" },
  { id: 1897, make: "Hyundai", name: "Veloster" },
  { id: 365, make: "Hyundai", name: "XG 30" },
  { id: 366, make: "Hyundai", name: "XG 350" },
  { id: 3587, make: "INEOS", name: "Grenadier" },
  { id: 1899, make: "Infiniti", name: "EX30" },
  { id: 1560, make: "Infiniti", name: "EX37" },
  { id: 371, make: "Infiniti", name: "FX" },
  { id: 1610, make: "Infiniti", name: "G37" },
  { id: 1900, make: "Infiniti", name: "M30" },
  { id: 1901, make: "Infiniti", name: "M35" },
  { id: 2680, make: "Infiniti", name: "Q30" },
  { id: 1788, make: "Infiniti", name: "Q50" },
  { id: 1802, make: "Infiniti", name: "Q60" },
  { id: 1799, make: "Infiniti", name: "Q70" },
  { id: 2829, make: "Infiniti", name: "QX30" },
  { id: 1800, make: "Infiniti", name: "QX50" },
  { id: 1801, make: "Infiniti", name: "QX70" },
  { id: 374, make: "Isuzu", name: "andere" },
  { id: 1018, make: "Isuzu", name: "D-Max" },
  { id: 373, make: "Isuzu", name: "Trooper" },
  { id: 1541, make: "Iveco", name: "andere" },
  { id: 1539, make: "Iveco", name: "Daily" },
  { id: 1538, make: "Iveco", name: "Massif" },
  { id: 3278, make: "JAC", name: "andere" },
  { id: 382, make: "Jaguar", name: "andere" },
  { id: 1903, make: "Jaguar", name: "Daimler" },
  { id: 3111, make: "Jaguar", name: "E-Pace" },
  { id: 1620, make: "Jaguar", name: "E-Type" },
  { id: 2831, make: "Jaguar", name: "F-Pace" },
  { id: 2158, make: "Jaguar", name: "F-Type" },
  { id: 3112, make: "Jaguar", name: "I-Pace" },
  { id: 1279, make: "Jaguar", name: "MK II" },
  { id: 381, make: "Jaguar", name: "Roadster" },
  { id: 375, make: "Jaguar", name: "S-Type" },
  { id: 376, make: "Jaguar", name: "X-Type" },
  { id: 2211, make: "Jaguar", name: "XE" },
  { id: 1280, make: "Jaguar", name: "XF" },
  { id: 377, make: "Jaguar", name: "XJ" },
  { id: 1281, make: "Jaguar", name: "XJ12" },
  { id: 1282, make: "Jaguar", name: "XJ40" },
  { id: 1283, make: "Jaguar", name: "XJ6" },
  { id: 378, make: "Jaguar", name: "XJ8" },
  { id: 1284, make: "Jaguar", name: "XJR" },
  { id: 1285, make: "Jaguar", name: "XJS" },
  { id: 1286, make: "Jaguar", name: "XJSC" },
  { id: 1022, make: "Jaguar", name: "XK" },
  { id: 379, make: "Jaguar", name: "XK8" },
  { id: 380, make: "Jaguar", name: "XKR" },
  { id: 388, make: "Jeep", name: "andere" },
  { id: 3493, make: "Jeep", name: "Avenger" },
  { id: 383, make: "Jeep", name: "Cherokee" },
  { id: 1904, make: "Jeep", name: "CJ" },
  { id: 387, make: "Jeep", name: "Commander" },
  { id: 1002, make: "Jeep", name: "Compass" },
  { id: 3374, make: "Jeep", name: "Gladiator" },
  { id: 384, make: "Jeep", name: "Grand Cherokee" },
  { id: 1061, make: "Jeep", name: "Patriot" },
  { id: 1288, make: "Jeep", name: "Renegade" },
  { id: 1289, make: "Jeep", name: "Wagoneer" },
  { id: 385, make: "Jeep", name: "Wrangler" },
  { id: 407, make: "Kia", name: "andere" },
  { id: 408, make: "Kia", name: "Besta" },
  { id: 390, make: "Kia", name: "Carens" },
  { id: 391, make: "Kia", name: "Carnival" },
  { id: 1905, make: "Kia", name: "Cee'd Sportswagon" },
  { id: 998, make: "Kia", name: "Ceed" },
  { id: 392, make: "Kia", name: "Cerato" },
  { id: 393, make: "Kia", name: "Clarus" },
  { id: 1291, make: "Kia", name: "Elan" },
  { id: 394, make: "Kia", name: "Joice" },
  { id: 1292, make: "Kia", name: "K2700" },
  { id: 396, make: "Kia", name: "Magentis" },
  { id: 2700, make: "Kia", name: "Niro" },
  { id: 397, make: "Kia", name: "Opirus" },
  { id: 2144, make: "Kia", name: "Optima" },
  { id: 398, make: "Kia", name: "Picanto" },
  { id: 399, make: "Kia", name: "Pregio" },
  { id: 400, make: "Kia", name: "Pride" },
  { id: 1065, make: "Kia", name: "ProCeed" },
  { id: 405, make: "Kia", name: "Retona" },
  { id: 401, make: "Kia", name: "Rio" },
  { id: 1295, make: "Kia", name: "Roadster" },
  { id: 1041, make: "Kia", name: "Sephia" },
  { id: 402, make: "Kia", name: "Shuma" },
  { id: 403, make: "Kia", name: "Sorento" },
  { id: 1553, make: "Kia", name: "Soul" },
  { id: 404, make: "Kia", name: "Sportage" },
  { id: 3083, make: "Kia", name: "Stinger" },
  { id: 3127, make: "Kia", name: "Stonic" },
  { id: 1611, make: "Kia", name: "Venga" },
  { id: 3269, make: "Kia", name: "XCeed" },
  { id: 1296, make: "Lada", name: "110" },
  { id: 1297, make: "Lada", name: "111" },
  { id: 1151, make: "Lada", name: "1117" },
  { id: 1299, make: "Lada", name: "1200" },
  { id: 2981, make: "Lada", name: "1500" },
  { id: 2431, make: "Lada", name: "2106" },
  { id: 1300, make: "Lada", name: "2107" },
  { id: 1909, make: "Lada", name: "2110" },
  { id: 1621, make: "Lada", name: "2111" },
  { id: 1622, make: "Lada", name: "2112" },
  { id: 1301, make: "Lada", name: "Aleko" },
  { id: 410, make: "Lada", name: "andere" },
  { id: 1792, make: "Lada", name: "Granta" },
  { id: 1019, make: "Lada", name: "Kalina" },
  { id: 409, make: "Lada", name: "Niva" },
  { id: 1302, make: "Lada", name: "Nova" },
  { id: 1304, make: "Lada", name: "Priora" },
  { id: 1303, make: "Lada", name: "Samara" },
  { id: 1778, make: "Lada", name: "Taiga" },
  { id: 2838, make: "Lada", name: "Urban" },
  { id: 2671, make: "Lada", name: "Vesta" },
  { id: 415, make: "Lamborghini", name: "andere" },
  { id: 1697, make: "Lamborghini", name: "Aventador" },
  { id: 1330, make: "Lamborghini", name: "Diablo" },
  { id: 412, make: "Lamborghini", name: "Gallardo" },
  { id: 2174, make: "Lamborghini", name: "Huracán" },
  { id: 413, make: "Lamborghini", name: "Murciélago" },
  { id: 3107, make: "Lamborghini", name: "Urus" },
  { id: 1310, make: "Lancia", name: "Beta" },
  { id: 425, make: "Lancia", name: "Dedra" },
  { id: 424, make: "Lancia", name: "Delta" },
  { id: 1311, make: "Lancia", name: "Flaminia" },
  { id: 2355, make: "Lancia", name: "Flavia" },
  { id: 1312, make: "Lancia", name: "Fulvia" },
  { id: 416, make: "Lancia", name: "Kappa" },
  { id: 417, make: "Lancia", name: "Lybra" },
  { id: 418, make: "Lancia", name: "Musa" },
  { id: 419, make: "Lancia", name: "Phedra" },
  { id: 1316, make: "Lancia", name: "Thema" },
  { id: 420, make: "Lancia", name: "Thesis" },
  { id: 1730, make: "Lancia", name: "Voyager" },
  { id: 421, make: "Lancia", name: "Y" },
  { id: 422, make: "Lancia", name: "Ypsilon" },
  { id: 423, make: "Lancia", name: "Zeta" },
  { id: 432, make: "Land Rover", name: "andere" },
  { id: 427, make: "Land Rover", name: "Defender" },
  { id: 428, make: "Land Rover", name: "Discovery" },
  { id: 2214, make: "Land Rover", name: "Discovery Sport" },
  { id: 429, make: "Land Rover", name: "Freelander" },
  { id: 430, make: "Land Rover", name: "Range Rover" },
  { id: 1681, make: "Land Rover", name: "Range Rover Evoque" },
  { id: 431, make: "Land Rover", name: "Range Rover Sport" },
  { id: 3041, make: "Land Rover", name: "Range Rover Velar" },
  { id: 1913, make: "Land Rover", name: "Serie III" },
  { id: 3604, make: "Leapmotor", name: "andere" },
  { id: 3589, make: "Leapmotor", name: "B10" },
  { id: 3592, make: "Leapmotor", name: "C10" },
  { id: 3588, make: "Leapmotor", name: "T03" },
  { id: 445, make: "Lexus", name: "andere" },
  { id: 1919, make: "Lexus", name: "CT 200h" },
  { id: 2843, make: "Lexus", name: "ES-Serie" },
  { id: 2846, make: "Lexus", name: "GS-Serie" },
  { id: 1319, make: "Lexus", name: "IS-F" },
  { id: 2852, make: "Lexus", name: "IS-Serie" },
  { id: 3554, make: "Lexus", name: "LBX" },
  { id: 3035, make: "Lexus", name: "LC-Serie" },
  { id: 3555, make: "Lexus", name: "LM" },
  { id: 2855, make: "Lexus", name: "LS-Serie" },
  { id: 3430, make: "Lexus", name: "NX 350" },
  { id: 3433, make: "Lexus", name: "NX 450" },
  { id: 2861, make: "Lexus", name: "NX-Serie" },
  { id: 2862, make: "Lexus", name: "RC-Serie" },
  { id: 2870, make: "Lexus", name: "RX-Serie" },
  { id: 3557, make: "Lexus", name: "RZ" },
  { id: 2874, make: "Lexus", name: "SC-Serie" },
  { id: 3130, make: "Lexus", name: "UX" },
  { id: 451, make: "Ligier", name: "andere" },
  { id: 1930, make: "Ligier", name: "JS 50" },
  { id: 3378, make: "Ligier", name: "JS 60" },
  { id: 1327, make: "Lincoln", name: "Continental" },
  { id: 459, make: "Lotus", name: "andere" },
  { id: 3558, make: "Lotus", name: "Eletre" },
  { id: 456, make: "Lotus", name: "Elise" },
  { id: 3559, make: "Lotus", name: "Emeya" },
  { id: 3434, make: "Lotus", name: "Emira" },
  { id: 460, make: "Lotus", name: "Esprit" },
  { id: 1934, make: "Lotus", name: "Europa" },
  { id: 1608, make: "Lotus", name: "Evora" },
  { id: 457, make: "Lotus", name: "Exige" },
  { id: 1935, make: "Lotus", name: "Super Seven" },
  { id: 3484, make: "Lynk&Co", name: "andere" },
  { id: 462, make: "Mahindra", name: "andere" },
  { id: 465, make: "Maserati", name: "3200" },
  { id: 1342, make: "Maserati", name: "Biturbo" },
  { id: 468, make: "Maserati", name: "Coupe" },
  { id: 1343, make: "Maserati", name: "Ghibli" },
  { id: 1936, make: "Maserati", name: "GranCabrio" },
  { id: 471, make: "Maserati", name: "GranSport" },
  { id: 1344, make: "Maserati", name: "GranTurismo" },
  { id: 3494, make: "Maserati", name: "Grecale" },
  { id: 1345, make: "Maserati", name: "Indy" },
  { id: 2694, make: "Maserati", name: "Levante" },
  { id: 3379, make: "Maserati", name: "MC20" },
  { id: 467, make: "Maserati", name: "Quattroporte" },
  { id: 469, make: "Maserati", name: "Spyder" },
  { id: 3602, make: "Maxus", name: "andere" },
  { id: 3596, make: "Maxus", name: "Deliver 9" },
  { id: 3594, make: "Maxus", name: "eDeliver 3" },
  { id: 3595, make: "Maxus", name: "eDeliver 9" },
  { id: 3597, make: "Maxus", name: "Euniq 5" },
  { id: 3598, make: "Maxus", name: "Euniq 6" },
  { id: 3601, make: "Maxus", name: "T60" },
  { id: 3600, make: "Maxus", name: "T90" },
  { id: 474, make: "Maybach", name: "57" },
  { id: 1350, make: "Maybach", name: "62" },
  { id: 475, make: "Maybach", name: "andere" },
  { id: 477, make: "Mazda", name: "121" },
  { id: 478, make: "Mazda", name: "2" },
  { id: 479, make: "Mazda", name: "3" },
  { id: 480, make: "Mazda", name: "323" },
  { id: 481, make: "Mazda", name: "5" },
  { id: 482, make: "Mazda", name: "6" },
  { id: 483, make: "Mazda", name: "626" },
  { id: 1351, make: "Mazda", name: "929" },
  { id: 495, make: "Mazda", name: "andere" },
  { id: 484, make: "Mazda", name: "B 2500" },
  { id: 1023, make: "Mazda", name: "BT-50" },
  { id: 2311, make: "Mazda", name: "CX-3" },
  { id: 3416, make: "Mazda", name: "CX-30" },
  { id: 1735, make: "Mazda", name: "CX-5" },
  { id: 1021, make: "Mazda", name: "CX-7" },
  { id: 1048, make: "Mazda", name: "CX-9" },
  { id: 485, make: "Mazda", name: "Demio" },
  { id: 486, make: "Mazda", name: "MPV" },
  { id: 494, make: "Mazda", name: "MX-3" },
  { id: 3311, make: "Mazda", name: "MX-30" },
  { id: 487, make: "Mazda", name: "MX-5" },
  { id: 476, make: "Mazda", name: "MX-6" },
  { id: 488, make: "Mazda", name: "Premacy" },
  { id: 493, make: "Mazda", name: "RX-7" },
  { id: 489, make: "Mazda", name: "RX-8" },
  { id: 490, make: "Mazda", name: "Tribute" },
  { id: 491, make: "Mazda", name: "Xedos" },
  { id: 1785, make: "McLaren", name: "12C" },
  { id: 2885, make: "McLaren", name: "540C" },
  { id: 2886, make: "McLaren", name: "570GT" },
  { id: 2888, make: "McLaren", name: "570S" },
  { id: 3380, make: "McLaren", name: "600LT" },
  { id: 1941, make: "McLaren", name: "650S Coupé" },
  { id: 1942, make: "McLaren", name: "650S Spider" },
  { id: 2892, make: "McLaren", name: "675LT" },
  { id: 3027, make: "McLaren", name: "720S" },
  { id: 3382, make: "McLaren", name: "750S" },
  { id: 3384, make: "McLaren", name: "765LT" },
  { id: 3387, make: "McLaren", name: "GT" },
  { id: 1943, make: "McLaren", name: "MP4-12C" },
  { id: 593, make: "Mercedes-Benz", name: "190" },
  { id: 1097, make: "Mercedes-Benz", name: "200" },
  { id: 594, make: "Mercedes-Benz", name: "220" },
  { id: 1098, make: "Mercedes-Benz", name: "230" },
  { id: 595, make: "Mercedes-Benz", name: "240" },
  { id: 1099, make: "Mercedes-Benz", name: "250" },
  { id: 1100, make: "Mercedes-Benz", name: "260" },
  { id: 1101, make: "Mercedes-Benz", name: "270" },
  { id: 1102, make: "Mercedes-Benz", name: "280" },
  { id: 1103, make: "Mercedes-Benz", name: "290" },
  { id: 1104, make: "Mercedes-Benz", name: "300" },
  { id: 1675, make: "Mercedes-Benz", name: "313 CDI" },
  { id: 1676, make: "Mercedes-Benz", name: "316 CDI" },
  { id: 1105, make: "Mercedes-Benz", name: "320" },
  { id: 1106, make: "Mercedes-Benz", name: "350" },
  { id: 1107, make: "Mercedes-Benz", name: "380" },
  { id: 1108, make: "Mercedes-Benz", name: "400" },
  { id: 1109, make: "Mercedes-Benz", name: "416" },
  { id: 1110, make: "Mercedes-Benz", name: "420" },
  { id: 1111, make: "Mercedes-Benz", name: "450" },
  { id: 1112, make: "Mercedes-Benz", name: "500" },
  { id: 1113, make: "Mercedes-Benz", name: "560" },
  { id: 1114, make: "Mercedes-Benz", name: "600" },
  { id: 975, make: "Mercedes-Benz", name: "A-Klasse" },
  { id: 2489, make: "Mercedes-Benz", name: "Actros" },
  { id: 619, make: "Mercedes-Benz", name: "andere" },
  { id: 2486, make: "Mercedes-Benz", name: "Atego" },
  { id: 976, make: "Mercedes-Benz", name: "B-Klasse" },
  { id: 977, make: "Mercedes-Benz", name: "C-Klasse" },
  { id: 1139, make: "Mercedes-Benz", name: "CE-Klasse" },
  { id: 1765, make: "Mercedes-Benz", name: "Citan" },
  { id: 978, make: "Mercedes-Benz", name: "CL-Klasse" },
  { id: 3390, make: "Mercedes-Benz", name: "CLA 35 AMG" },
  { id: 1773, make: "Mercedes-Benz", name: "CLA-Klasse" },
  { id: 1116, make: "Mercedes-Benz", name: "CLC-Klasse" },
  { id: 3561, make: "Mercedes-Benz", name: "CLE-Klasse" },
  { id: 979, make: "Mercedes-Benz", name: "CLK-Klasse" },
  { id: 980, make: "Mercedes-Benz", name: "CLS-Klasse" },
  { id: 981, make: "Mercedes-Benz", name: "E-Klasse" },
  { id: 3391, make: "Mercedes-Benz", name: "EQA" },
  { id: 3392, make: "Mercedes-Benz", name: "EQB" },
  { id: 3270, make: "Mercedes-Benz", name: "EQC" },
  { id: 3393, make: "Mercedes-Benz", name: "EQE" },
  { id: 3394, make: "Mercedes-Benz", name: "EQS" },
  { id: 3560, make: "Mercedes-Benz", name: "EQT" },
  { id: 3395, make: "Mercedes-Benz", name: "EQV" },
  { id: 982, make: "Mercedes-Benz", name: "G-Klasse" },
  { id: 983, make: "Mercedes-Benz", name: "GL-Klasse" },
  { id: 3396, make: "Mercedes-Benz", name: "GLA 35 AMG" },
  { id: 1974, make: "Mercedes-Benz", name: "GLA-Klasse" },
  { id: 3258, make: "Mercedes-Benz", name: "GLB-Klasse" },
  { id: 2714, make: "Mercedes-Benz", name: "GLC-Klasse" },
  { id: 3397, make: "Mercedes-Benz", name: "GLE 580" },
  { id: 2534, make: "Mercedes-Benz", name: "GLE-Klasse" },
  { id: 1527, make: "Mercedes-Benz", name: "GLK-Klasse" },
  { id: 2727, make: "Mercedes-Benz", name: "GLS-Klasse" },
  { id: 3136, make: "Mercedes-Benz", name: "GT-Klasse" },
  { id: 2739, make: "Mercedes-Benz", name: "MB 100" },
  { id: 984, make: "Mercedes-Benz", name: "ML-Klasse" },
  { id: 985, make: "Mercedes-Benz", name: "R-Klasse" },
  { id: 3398, make: "Mercedes-Benz", name: "S 580" },
  { id: 3399, make: "Mercedes-Benz", name: "S 680" },
  { id: 986, make: "Mercedes-Benz", name: "S-Klasse" },
  { id: 987, make: "Mercedes-Benz", name: "SL-Klasse" },
  { id: 2741, make: "Mercedes-Benz", name: "SLC-Klasse" },
  { id: 988, make: "Mercedes-Benz", name: "SLK-Klasse" },
  { id: 584, make: "Mercedes-Benz", name: "SLR" },
  { id: 1593, make: "Mercedes-Benz", name: "SLS" },
  { id: 3542, make: "Mercedes-Benz", name: "T-Klasse" },
  { id: 1141, make: "Mercedes-Benz", name: "Transporter" },
  { id: 1803, make: "Mercedes-Benz", name: "V-Klasse" },
  { id: 3140, make: "Mercedes-Benz", name: "X-Klasse" },
  { id: 641, make: "MG", name: "andere" },
  { id: 3400, make: "MG", name: "EHS" },
  { id: 3435, make: "MG", name: "HS" },
  { id: 3401, make: "MG", name: "Marvel R" },
  { id: 3495, make: "MG", name: "MG4" },
  { id: 3402, make: "MG", name: "MG5" },
  { id: 1354, make: "MG", name: "MGA" },
  { id: 1355, make: "MG", name: "MGB" },
  { id: 635, make: "MG", name: "MGF" },
  { id: 637, make: "MG", name: "TF" },
  { id: 638, make: "MG", name: "ZR" },
  { id: 639, make: "MG", name: "ZS" },
  { id: 640, make: "MG", name: "ZT" },
  { id: 636, make: "MG", name: "ZT-T" },
  { id: 1567, make: "Microcar", name: "andere" },
  { id: 646, make: "Mini", name: "andere" },
  { id: 2072, make: "Mini", name: "Cabrio Serie" },
  { id: 1020, make: "Mini", name: "Clubman" },
  { id: 1768, make: "Mini", name: "Clubvan" },
  { id: 643, make: "Mini", name: "Cooper" },
  { id: 2014, make: "Mini", name: "Cooper D" },
  { id: 999, make: "Mini", name: "Cooper S" },
  { id: 2002, make: "Mini", name: "Cooper S Clubman" },
  { id: 2009, make: "Mini", name: "Cooper S Countryman" },
  { id: 2015, make: "Mini", name: "Cooper SD" },
  { id: 1634, make: "Mini", name: "Countryman" },
  { id: 2113, make: "Mini", name: "Coupe Serie" },
  { id: 2016, make: "Mini", name: "John Cooper Works" },
  { id: 2903, make: "Mini", name: "Mini" },
  { id: 645, make: "Mini", name: "One" },
  { id: 2017, make: "Mini", name: "One D" },
  { id: 3232, make: "Mini", name: "One First" },
  { id: 1767, make: "Mini", name: "Paceman" },
  { id: 2118, make: "Mini", name: "Roadster Serie" },
  { id: 665, make: "Mitsubishi", name: "3000 GT" },
  { id: 664, make: "Mitsubishi", name: "andere" },
  { id: 1638, make: "Mitsubishi", name: "ASX" },
  { id: 666, make: "Mitsubishi", name: "Canter" },
  { id: 647, make: "Mitsubishi", name: "Carisma" },
  { id: 648, make: "Mitsubishi", name: "Colt" },
  { id: 649, make: "Mitsubishi", name: "Eclipse" },
  { id: 3084, make: "Mitsubishi", name: "Eclipse Cross" },
  { id: 1533, make: "Mitsubishi", name: "Fuso" },
  { id: 650, make: "Mitsubishi", name: "Galant" },
  { id: 652, make: "Mitsubishi", name: "Grandis" },
  { id: 2024, make: "Mitsubishi", name: "i-MiEV" },
  { id: 653, make: "Mitsubishi", name: "L200" },
  { id: 663, make: "Mitsubishi", name: "L300" },
  { id: 1361, make: "Mitsubishi", name: "L400" },
  { id: 654, make: "Mitsubishi", name: "Lancer" },
  { id: 655, make: "Mitsubishi", name: "Outlander" },
  { id: 656, make: "Mitsubishi", name: "Pajero" },
  { id: 657, make: "Mitsubishi", name: "Pajero Pinin" },
  { id: 3233, make: "Mitsubishi", name: "Plug-in Hybrid Outlander" },
  { id: 1364, make: "Mitsubishi", name: "Sapporo" },
  { id: 667, make: "Mitsubishi", name: "Sigma" },
  { id: 659, make: "Mitsubishi", name: "Space Gear" },
  { id: 660, make: "Mitsubishi", name: "Space Runner" },
  { id: 661, make: "Mitsubishi", name: "Space Star" },
  { id: 662, make: "Mitsubishi", name: "Space Wagon" },
  { id: 2025, make: "Morgan", name: "4/4" },
  { id: 1511, make: "Morgan", name: "Aero 8" },
  { id: 1512, make: "Morgan", name: "Plus 4" },
  { id: 3403, make: "Morgan", name: "Plus 6" },
  { id: 1513, make: "Morgan", name: "Plus 8" },
  { id: 1743, make: "Morgan", name: "Roadster" },
  { id: 2232, make: "Morgan", name: "Threewheeler" },
  { id: 3539, make: "NIO", name: "ET5" },
  { id: 3540, make: "NIO", name: "ET7" },
  { id: 687, make: "Nissan", name: "100NX" },
  { id: 688, make: "Nissan", name: "200SX" },
  { id: 693, make: "Nissan", name: "300ZX" },
  { id: 669, make: "Nissan", name: "350Z" },
  { id: 1575, make: "Nissan", name: "370Z" },
  { id: 670, make: "Nissan", name: "Almera" },
  { id: 671, make: "Nissan", name: "Almera Tino" },
  { id: 692, make: "Nissan", name: "andere" },
  { id: 3436, make: "Nissan", name: "Ariya" },
  { id: 1370, make: "Nissan", name: "Bluebird" },
  { id: 1371, make: "Nissan", name: "Cabstar" },
  { id: 1564, make: "Nissan", name: "Cube" },
  { id: 2027, make: "Nissan", name: "Evalia" },
  { id: 2530, make: "Nissan", name: "Figaro" },
  { id: 1374, make: "Nissan", name: "Frontier" },
  { id: 1581, make: "Nissan", name: "GT-R" },
  { id: 672, make: "Nissan", name: "Interstar" },
  { id: 1640, make: "Nissan", name: "Juke" },
  { id: 673, make: "Nissan", name: "Kubistar" },
  { id: 1375, make: "Nissan", name: "Laurel" },
  { id: 1615, make: "Nissan", name: "Leaf" },
  { id: 674, make: "Nissan", name: "Maxima" },
  { id: 675, make: "Nissan", name: "Micra" },
  { id: 676, make: "Nissan", name: "Murano" },
  { id: 690, make: "Nissan", name: "Navara" },
  { id: 691, make: "Nissan", name: "Note" },
  { id: 1609, make: "Nissan", name: "NP300" },
  { id: 1599, make: "Nissan", name: "NV200" },
  { id: 3404, make: "Nissan", name: "NV250" },
  { id: 3144, make: "Nissan", name: "NV300" },
  { id: 1727, make: "Nissan", name: "NV400" },
  { id: 677, make: "Nissan", name: "Pathfinder" },
  { id: 678, make: "Nissan", name: "Patrol" },
  { id: 679, make: "Nissan", name: "PickUp" },
  { id: 1591, make: "Nissan", name: "Pixo" },
  { id: 695, make: "Nissan", name: "Prairie" },
  { id: 680, make: "Nissan", name: "Primastar" },
  { id: 681, make: "Nissan", name: "Primera" },
  { id: 2233, make: "Nissan", name: "Pulsar" },
  { id: 1000, make: "Nissan", name: "Qashqai" },
  { id: 2028, make: "Nissan", name: "Qashqai +2" },
  { id: 3234, make: "Nissan", name: "Qashqai+2" },
  { id: 682, make: "Nissan", name: "Serena" },
  { id: 2030, make: "Nissan", name: "Silvia" },
  { id: 668, make: "Nissan", name: "Sunny" },
  { id: 683, make: "Nissan", name: "Terrano" },
  { id: 1051, make: "Nissan", name: "Tiida" },
  { id: 3437, make: "Nissan", name: "Townstar" },
  { id: 694, make: "Nissan", name: "Trade" },
  { id: 2031, make: "Nissan", name: "Urvan" },
  { id: 689, make: "Nissan", name: "Vanette" },
  { id: 686, make: "Nissan", name: "X-Trail" },
  { id: 2032, make: "NSU", name: "andere" },
  { id: 1764, make: "Opel", name: "Adam" },
  { id: 702, make: "Opel", name: "Agila" },
  { id: 1808, make: "Opel", name: "Ampera" },
  { id: 3235, make: "Opel", name: "Ampera-e" },
  { id: 725, make: "Opel", name: "andere" },
  { id: 711, make: "Opel", name: "Antara" },
  { id: 726, make: "Opel", name: "Arena" },
  { id: 721, make: "Opel", name: "Ascona" },
  { id: 703, make: "Opel", name: "Astra" },
  { id: 698, make: "Opel", name: "Calibra" },
  { id: 699, make: "Opel", name: "Campo" },
  { id: 1772, make: "Opel", name: "Cascada" },
  { id: 704, make: "Opel", name: "Combo" },
  { id: 705, make: "Opel", name: "Corsa" },
  { id: 3485, make: "Opel", name: "Crossland" },
  { id: 3020, make: "Opel", name: "Crossland X" },
  { id: 727, make: "Opel", name: "Diplomat" },
  { id: 706, make: "Opel", name: "Frontera" },
  { id: 3486, make: "Opel", name: "Grandland" },
  { id: 3077, make: "Opel", name: "Grandland X" },
  { id: 723, make: "Opel", name: "GT" },
  { id: 1382, make: "Opel", name: "Insignia" },
  { id: 1790, make: "Opel", name: "Insignia Country Tourer" },
  { id: 3236, make: "Opel", name: "Insignia CT" },
  { id: 697, make: "Opel", name: "Kadett" },
  { id: 2994, make: "Opel", name: "Kapitän" },
  { id: 2241, make: "Opel", name: "Karl" },
  { id: 700, make: "Opel", name: "Manta" },
  { id: 707, make: "Opel", name: "Meriva" },
  { id: 1753, make: "Opel", name: "Mokka" },
  { id: 3237, make: "Opel", name: "Mokka X" },
  { id: 724, make: "Opel", name: "Monterey" },
  { id: 1380, make: "Opel", name: "Monza" },
  { id: 708, make: "Opel", name: "Movano" },
  { id: 709, make: "Opel", name: "Omega" },
  { id: 1383, make: "Opel", name: "Pick Up Sportscap" },
  { id: 701, make: "Opel", name: "Rekord" },
  { id: 3438, make: "Opel", name: "Rocks-e" },
  { id: 719, make: "Opel", name: "Senator" },
  { id: 710, make: "Opel", name: "Signum" },
  { id: 718, make: "Opel", name: "Sintra" },
  { id: 712, make: "Opel", name: "Speedster" },
  { id: 713, make: "Opel", name: "Tigra" },
  { id: 714, make: "Opel", name: "Vectra" },
  { id: 715, make: "Opel", name: "Vivaro" },
  { id: 716, make: "Opel", name: "Zafira" },
  { id: 3238, make: "Opel", name: "Zafira Life" },
  { id: 1731, make: "Opel", name: "Zafira Tourer" },
  { id: 3533, make: "ORA", name: "andere" },
  { id: 732, make: "Peugeot", name: "1007" },
  { id: 733, make: "Peugeot", name: "106" },
  { id: 734, make: "Peugeot", name: "107" },
  { id: 2140, make: "Peugeot", name: "108" },
  { id: 1775, make: "Peugeot", name: "2008" },
  { id: 748, make: "Peugeot", name: "205" },
  { id: 735, make: "Peugeot", name: "206" },
  { id: 749, make: "Peugeot", name: "207" },
  { id: 1742, make: "Peugeot", name: "208" },
  { id: 1579, make: "Peugeot", name: "3008" },
  { id: 2034, make: "Peugeot", name: "301" },
  { id: 1386, make: "Peugeot", name: "304" },
  { id: 1387, make: "Peugeot", name: "305" },
  { id: 736, make: "Peugeot", name: "306" },
  { id: 737, make: "Peugeot", name: "307" },
  { id: 1006, make: "Peugeot", name: "308" },
  { id: 731, make: "Peugeot", name: "309" },
  { id: 1013, make: "Peugeot", name: "4007" },
  { id: 1752, make: "Peugeot", name: "4008" },
  { id: 752, make: "Peugeot", name: "405" },
  { id: 738, make: "Peugeot", name: "406" },
  { id: 739, make: "Peugeot", name: "407" },
  { id: 3497, make: "Peugeot", name: "408" },
  { id: 1583, make: "Peugeot", name: "5008" },
  { id: 751, make: "Peugeot", name: "505" },
  { id: 1694, make: "Peugeot", name: "508" },
  { id: 1389, make: "Peugeot", name: "604" },
  { id: 747, make: "Peugeot", name: "605" },
  { id: 741, make: "Peugeot", name: "607" },
  { id: 742, make: "Peugeot", name: "806" },
  { id: 743, make: "Peugeot", name: "807" },
  { id: 750, make: "Peugeot", name: "andere" },
  { id: 1090, make: "Peugeot", name: "Bipper" },
  { id: 2035, make: "Peugeot", name: "Bipper Tepee" },
  { id: 744, make: "Peugeot", name: "Boxer" },
  { id: 745, make: "Peugeot", name: "Expert" },
  { id: 1736, make: "Peugeot", name: "iOn" },
  { id: 1390, make: "Peugeot", name: "J5" },
  { id: 746, make: "Peugeot", name: "Partner" },
  { id: 1617, make: "Peugeot", name: "RCZ" },
  { id: 3145, make: "Peugeot", name: "Rifter" },
  { id: 2036, make: "Peugeot", name: "TePee" },
  { id: 2913, make: "Peugeot", name: "Traveller" },
  { id: 728, make: "PGO", name: "Speedster" },
  { id: 1519, make: "Piaggio", name: "Porter" },
  { id: 753, make: "Plymouth", name: "andere" },
  { id: 754, make: "Plymouth", name: "Prowler" },
  { id: 3441, make: "Polestar", name: "1" },
  { id: 3442, make: "Polestar", name: "2" },
  { id: 3498, make: "Polestar", name: "3" },
  { id: 1391, make: "Pontiac", name: "Bonneville" },
  { id: 1392, make: "Pontiac", name: "Fiero" },
  { id: 756, make: "Pontiac", name: "Firebird" },
  { id: 1395, make: "Pontiac", name: "Grand-Prix" },
  { id: 1403, make: "Porsche", name: "356" },
  { id: 762, make: "Porsche", name: "911" },
  { id: 1404, make: "Porsche", name: "912" },
  { id: 768, make: "Porsche", name: "914" },
  { id: 759, make: "Porsche", name: "924" },
  { id: 771, make: "Porsche", name: "928" },
  { id: 769, make: "Porsche", name: "944" },
  { id: 1406, make: "Porsche", name: "962" },
  { id: 1407, make: "Porsche", name: "968" },
  { id: 3239, make: "Porsche", name: "992" },
  { id: 770, make: "Porsche", name: "andere" },
  { id: 764, make: "Porsche", name: "Boxster" },
  { id: 765, make: "Porsche", name: "Carrera" },
  { id: 2045, make: "Porsche", name: "Carrera GT" },
  { id: 766, make: "Porsche", name: "Cayenne" },
  { id: 2308, make: "Porsche", name: "Cayenne GTS" },
  { id: 767, make: "Porsche", name: "Cayman" },
  { id: 1798, make: "Porsche", name: "Macan" },
  { id: 1561, make: "Porsche", name: "Panamera" },
  { id: 3253, make: "Porsche", name: "Taycan" },
  { id: 772, make: "Proton", name: "Serie 300" },
  { id: 3146, make: "Renault", name: "Alaskan" },
  { id: 2046, make: "Renault", name: "Alpine A110" },
  { id: 796, make: "Renault", name: "andere" },
  { id: 3405, make: "Renault", name: "Arkana" },
  { id: 3499, make: "Renault", name: "Austral" },
  { id: 777, make: "Renault", name: "Avantime" },
  { id: 1777, make: "Renault", name: "Captur" },
  { id: 778, make: "Renault", name: "Clio" },
  { id: 780, make: "Renault", name: "Espace" },
  { id: 1410, make: "Renault", name: "Express" },
  { id: 1641, make: "Renault", name: "Fluence" },
  { id: 2916, make: "Renault", name: "Fuego" },
  { id: 781, make: "Renault", name: "Grand Espace" },
  { id: 1412, make: "Renault", name: "Grand Modus" },
  { id: 782, make: "Renault", name: "Grand Scenic" },
  { id: 2260, make: "Renault", name: "Kadjar" },
  { id: 783, make: "Renault", name: "Kangoo" },
  { id: 1413, make: "Renault", name: "Koleos" },
  { id: 784, make: "Renault", name: "Laguna" },
  { id: 1643, make: "Renault", name: "Latitude" },
  { id: 799, make: "Renault", name: "Mascott" },
  { id: 785, make: "Renault", name: "Master" },
  { id: 786, make: "Renault", name: "Megane" },
  { id: 787, make: "Renault", name: "Modus" },
  { id: 1414, make: "Renault", name: "R 11" },
  { id: 1416, make: "Renault", name: "R 18" },
  { id: 2048, make: "Renault", name: "R 19" },
  { id: 2049, make: "Renault", name: "R 21" },
  { id: 1418, make: "Renault", name: "R 25" },
  { id: 2050, make: "Renault", name: "R 4" },
  { id: 797, make: "Renault", name: "R 5" },
  { id: 2052, make: "Renault", name: "R 9" },
  { id: 3562, make: "Renault", name: "Rafale" },
  { id: 798, make: "Renault", name: "Rapid" },
  { id: 793, make: "Renault", name: "Safrane" },
  { id: 788, make: "Renault", name: "Scenic" },
  { id: 792, make: "Renault", name: "Spider" },
  { id: 2578, make: "Renault", name: "Talisman" },
  { id: 789, make: "Renault", name: "Trafic" },
  { id: 790, make: "Renault", name: "Twingo" },
  { id: 1770, make: "Renault", name: "Twizy" },
  { id: 791, make: "Renault", name: "Vel Satis" },
  { id: 1616, make: "Renault", name: "Wind" },
  { id: 2053, make: "Renault", name: "ZOE" },
  { id: 800, make: "Rolls-Royce", name: "andere" },
  { id: 3240, make: "Rolls-Royce", name: "Cullinan" },
  { id: 2919, make: "Rolls-Royce", name: "Dawn" },
  { id: 1601, make: "Rolls-Royce", name: "Ghost" },
  { id: 1042, make: "Rolls-Royce", name: "Phantom" },
  { id: 2055, make: "Rolls-Royce", name: "Silver Cloud" },
  { id: 1421, make: "Rolls-Royce", name: "Silver Seraph" },
  { id: 1422, make: "Rolls-Royce", name: "Silver Shadow" },
  { id: 1423, make: "Rolls-Royce", name: "Silver Spirit" },
  { id: 1784, make: "Rolls-Royce", name: "Wraith" },
  { id: 1425, make: "Rover", name: "111" },
  { id: 1426, make: "Rover", name: "114" },
  { id: 1427, make: "Rover", name: "213" },
  { id: 814, make: "Rover", name: "214" },
  { id: 805, make: "Rover", name: "216" },
  { id: 817, make: "Rover", name: "220" },
  { id: 806, make: "Rover", name: "25" },
  { id: 1429, make: "Rover", name: "414" },
  { id: 804, make: "Rover", name: "416" },
  { id: 812, make: "Rover", name: "420" },
  { id: 807, make: "Rover", name: "45" },
  { id: 1053, make: "Rover", name: "618" },
  { id: 811, make: "Rover", name: "620" },
  { id: 1054, make: "Rover", name: "623" },
  { id: 808, make: "Rover", name: "75" },
  { id: 1433, make: "Rover", name: "825" },
  { id: 818, make: "Rover", name: "827" },
  { id: 816, make: "Rover", name: "andere" },
  { id: 802, make: "Rover", name: "Mini" },
  { id: 809, make: "Rover", name: "Rover" },
  { id: 810, make: "Rover", name: "Streetwise" },
  { id: 820, make: "Saab", name: "9-3" },
  { id: 2060, make: "Saab", name: "9-4X" },
  { id: 821, make: "Saab", name: "9-5" },
  { id: 1438, make: "Saab", name: "90" },
  { id: 819, make: "Saab", name: "900" },
  { id: 2062, make: "Saab", name: "9000" },
  { id: 1009, make: "Saab", name: "99" },
  { id: 2454, make: "Santana", name: "PS-10" },
  { id: 828, make: "Seat", name: "Alhambra" },
  { id: 829, make: "Seat", name: "Altea" },
  { id: 3147, make: "Seat", name: "Arona" },
  { id: 830, make: "Seat", name: "Arosa" },
  { id: 2693, make: "Seat", name: "Ateca" },
  { id: 831, make: "Seat", name: "Cordoba" },
  { id: 1566, make: "Seat", name: "Exeo" },
  { id: 832, make: "Seat", name: "Ibiza" },
  { id: 835, make: "Seat", name: "Inca" },
  { id: 833, make: "Seat", name: "Leon" },
  { id: 1440, make: "Seat", name: "Malaga" },
  { id: 827, make: "Seat", name: "Marbella" },
  { id: 1751, make: "Seat", name: "Mii" },
  { id: 3148, make: "Seat", name: "Tarraco" },
  { id: 834, make: "Seat", name: "Toledo" },
  { id: 842, make: "Skoda", name: "105" },
  { id: 1442, make: "Skoda", name: "120" },
  { id: 1443, make: "Skoda", name: "130" },
  { id: 1444, make: "Skoda", name: "135" },
  { id: 844, make: "Skoda", name: "andere" },
  { id: 1744, make: "Skoda", name: "Citigo" },
  { id: 3406, make: "Skoda", name: "Enyaq" },
  { id: 839, make: "Skoda", name: "Fabia" },
  { id: 1445, make: "Skoda", name: "Favorit" },
  { id: 843, make: "Skoda", name: "Felicia" },
  { id: 3275, make: "Skoda", name: "Kamiq" },
  { id: 3032, make: "Skoda", name: "Karoq" },
  { id: 2957, make: "Skoda", name: "Kodiaq" },
  { id: 840, make: "Skoda", name: "Octavia" },
  { id: 1447, make: "Skoda", name: "Pick-up" },
  { id: 1055, make: "Skoda", name: "Praktik" },
  { id: 1766, make: "Skoda", name: "Rapid" },
  { id: 837, make: "Skoda", name: "Roomster" },
  { id: 3241, make: "Skoda", name: "Scala" },
  { id: 841, make: "Skoda", name: "Superb" },
  { id: 1572, make: "Skoda", name: "Yeti" },
  { id: 851, make: "Smart", name: "andere" },
  { id: 845, make: "Smart", name: "Crossblade" },
  { id: 847, make: "Smart", name: "forfour" },
  { id: 848, make: "Smart", name: "ForTwo" },
  { id: 849, make: "Smart", name: "roadster" },
  { id: 859, make: "SsangYong", name: "Actyon" },
  { id: 858, make: "SsangYong", name: "andere" },
  { id: 854, make: "SsangYong", name: "Korando" },
  { id: 855, make: "SsangYong", name: "Kyron" },
  { id: 853, make: "SsangYong", name: "Musso Sports" },
  { id: 856, make: "SsangYong", name: "Rexton" },
  { id: 857, make: "SsangYong", name: "Rodius" },
  { id: 2263, make: "SsangYong", name: "Tivoli" },
  { id: 3564, make: "SsangYong", name: "Torres" },
  { id: 2697, make: "SsangYong", name: "XLV" },
  { id: 2235, make: "Subaru", name: "1800" },
  { id: 867, make: "Subaru", name: "andere" },
  { id: 866, make: "Subaru", name: "B9 Tribeca" },
  { id: 1762, make: "Subaru", name: "BRZ" },
  { id: 3565, make: "Subaru", name: "Crosstrek" },
  { id: 860, make: "Subaru", name: "Forester" },
  { id: 861, make: "Subaru", name: "Impreza" },
  { id: 862, make: "Subaru", name: "Justy" },
  { id: 863, make: "Subaru", name: "Legacy" },
  { id: 2574, make: "Subaru", name: "Levorg" },
  { id: 2070, make: "Subaru", name: "Libero" },
  { id: 864, make: "Subaru", name: "Outback" },
  { id: 3500, make: "Subaru", name: "Solterra" },
  { id: 1449, make: "Subaru", name: "SVX" },
  { id: 1682, make: "Subaru", name: "Trezia" },
  { id: 2071, make: "Subaru", name: "Tribeca" },
  { id: 2269, make: "Subaru", name: "WRX STI" },
  { id: 1733, make: "Subaru", name: "XV" },
  { id: 3407, make: "Suzuki", name: "Across" },
  { id: 873, make: "Suzuki", name: "Alto" },
  { id: 883, make: "Suzuki", name: "andere" },
  { id: 874, make: "Suzuki", name: "Baleno" },
  { id: 885, make: "Suzuki", name: "Carry" },
  { id: 2238, make: "Suzuki", name: "Celerio" },
  { id: 875, make: "Suzuki", name: "Grand Vitara" },
  { id: 876, make: "Suzuki", name: "Ignis" },
  { id: 877, make: "Suzuki", name: "Jimny" },
  { id: 1481, make: "Suzuki", name: "Kizashi" },
  { id: 878, make: "Suzuki", name: "Liana" },
  { id: 871, make: "Suzuki", name: "Samurai" },
  { id: 872, make: "Suzuki", name: "SJ" },
  { id: 1069, make: "Suzuki", name: "Splash" },
  { id: 1452, make: "Suzuki", name: "Super-Carry" },
  { id: 3408, make: "Suzuki", name: "Swace" },
  { id: 879, make: "Suzuki", name: "Swift" },
  { id: 884, make: "Suzuki", name: "SX4" },
  { id: 2074, make: "Suzuki", name: "SX4 S-Cross" },
  { id: 880, make: "Suzuki", name: "Vitara" },
  { id: 881, make: "Suzuki", name: "Wagon R+" },
  { id: 1515, make: "Talbot", name: "Samba" },
  { id: 1594, make: "Tata", name: "Indica" },
  { id: 1696, make: "Tesla", name: "andere" },
  { id: 2925, make: "Tesla", name: "Model 3" },
  { id: 2244, make: "Tesla", name: "Model S" },
  { id: 2250, make: "Tesla", name: "Model X" },
  { id: 3409, make: "Tesla", name: "Model Y" },
  { id: 904, make: "Toyota", name: "4Runner" },
  { id: 906, make: "Toyota", name: "andere" },
  { id: 1001, make: "Toyota", name: "Auris" },
  { id: 2078, make: "Toyota", name: "Auris Touring Sports" },
  { id: 890, make: "Toyota", name: "Avensis" },
  { id: 2079, make: "Toyota", name: "Avensis Verso" },
  { id: 891, make: "Toyota", name: "Aygo" },
  { id: 3501, make: "Toyota", name: "bZ4X" },
  { id: 2930, make: "Toyota", name: "C-HR" },
  { id: 892, make: "Toyota", name: "Camry" },
  { id: 886, make: "Toyota", name: "Carina" },
  { id: 893, make: "Toyota", name: "Celica" },
  { id: 894, make: "Toyota", name: "Corolla" },
  { id: 1010, make: "Toyota", name: "Corolla Verso" },
  { id: 3566, make: "Toyota", name: "GR86" },
  { id: 1745, make: "Toyota", name: "GT86" },
  { id: 895, make: "Toyota", name: "Hiace" },
  { id: 2081, make: "Toyota", name: "Highlander" },
  { id: 896, make: "Toyota", name: "Hilux" },
  { id: 1555, make: "Toyota", name: "iQ" },
  { id: 897, make: "Toyota", name: "Land Cruiser" },
  { id: 2937, make: "Toyota", name: "Mirai" },
  { id: 898, make: "Toyota", name: "MR 2" },
  { id: 888, make: "Toyota", name: "Paseo" },
  { id: 899, make: "Toyota", name: "Picnic" },
  { id: 900, make: "Toyota", name: "Previa" },
  { id: 901, make: "Toyota", name: "Prius" },
  { id: 1746, make: "Toyota", name: "Prius+" },
  { id: 1789, make: "Toyota", name: "Proace" },
  { id: 902, make: "Toyota", name: "RAV 4" },
  { id: 1457, make: "Toyota", name: "Sienna" },
  { id: 887, make: "Toyota", name: "Starlet" },
  { id: 1458, make: "Toyota", name: "Supra" },
  { id: 2082, make: "Toyota", name: "Tacoma" },
  { id: 907, make: "Toyota", name: "Tercel" },
  { id: 1459, make: "Toyota", name: "Tundra" },
  { id: 1589, make: "Toyota", name: "Urban Cruiser" },
  { id: 1590, make: "Toyota", name: "Verso" },
  { id: 2083, make: "Toyota", name: "Verso-S" },
  { id: 903, make: "Toyota", name: "Yaris" },
  { id: 2084, make: "Trabant", name: "601" },
  { id: 909, make: "Trabant", name: "andere" },
  { id: 912, make: "Triumph", name: "andere" },
  { id: 1464, make: "Triumph", name: "TR6" },
  { id: 1466, make: "Triumph", name: "TR8" },
  { id: 932, make: "Volvo", name: "240" },
  { id: 1468, make: "Volvo", name: "245" },
  { id: 1471, make: "Volvo", name: "340" },
  { id: 1472, make: "Volvo", name: "360" },
  { id: 919, make: "Volvo", name: "440" },
  { id: 931, make: "Volvo", name: "460" },
  { id: 915, make: "Volvo", name: "480" },
  { id: 918, make: "Volvo", name: "740" },
  { id: 916, make: "Volvo", name: "760" },
  { id: 930, make: "Volvo", name: "850" },
  { id: 914, make: "Volvo", name: "940" },
  { id: 934, make: "Volvo", name: "960" },
  { id: 929, make: "Volvo", name: "andere" },
  { id: 935, make: "Volvo", name: "C30" },
  { id: 3440, make: "Volvo", name: "C40" },
  { id: 920, make: "Volvo", name: "C70" },
  { id: 3548, make: "Volvo", name: "EX30" },
  { id: 3568, make: "Volvo", name: "EX40" },
  { id: 3503, make: "Volvo", name: "EX90" },
  { id: 921, make: "Volvo", name: "S40" },
  { id: 922, make: "Volvo", name: "S60" },
  { id: 3247, make: "Volvo", name: "S60 Cross Country" },
  { id: 917, make: "Volvo", name: "S70" },
  { id: 923, make: "Volvo", name: "S80" },
  { id: 2105, make: "Volvo", name: "S90" },
  { id: 924, make: "Volvo", name: "V40" },
  { id: 1769, make: "Volvo", name: "V40 Cross Country" },
  { id: 925, make: "Volvo", name: "V50" },
  { id: 1726, make: "Volvo", name: "V60" },
  { id: 3248, make: "Volvo", name: "V60 Cross Country" },
  { id: 926, make: "Volvo", name: "V70" },
  { id: 1056, make: "Volvo", name: "V90" },
  { id: 3249, make: "Volvo", name: "V90 Cross Country" },
  { id: 2962, make: "Volvo", name: "XC40" },
  { id: 1092, make: "Volvo", name: "XC60" },
  { id: 927, make: "Volvo", name: "XC70" },
  { id: 928, make: "Volvo", name: "XC90" },
  { id: 1690, make: "VW", name: "1303" },
  { id: 1631, make: "VW", name: "Amarok" },
  { id: 963, make: "VW", name: "andere" },
  { id: 3074, make: "VW", name: "Arteon" },
  { id: 964, make: "VW", name: "Beetle" },
  { id: 944, make: "VW", name: "Bora" },
  { id: 937, make: "VW", name: "Caddy" },
  { id: 945, make: "VW", name: "California" },
  { id: 946, make: "VW", name: "Caravelle" },
  { id: 1734, make: "VW", name: "CC" },
  { id: 936, make: "VW", name: "Corrado" },
  { id: 1547, make: "VW", name: "Crafter" },
  { id: 962, make: "VW", name: "Eos" },
  { id: 947, make: "VW", name: "Fox" },
  { id: 948, make: "VW", name: "Golf" },
  { id: 1544, make: "VW", name: "Golf Plus" },
  { id: 2167, make: "VW", name: "Golf Sportsvan" },
  { id: 1545, make: "VW", name: "Golf Variant" },
  { id: 3410, make: "VW", name: "ID.3" },
  { id: 3411, make: "VW", name: "ID.4" },
  { id: 3412, make: "VW", name: "ID.5" },
  { id: 3569, make: "VW", name: "ID.7" },
  { id: 3439, make: "VW", name: "ID.Buzz" },
  { id: 3541, make: "VW", name: "ID.Buzz Cargo" },
  { id: 949, make: "VW", name: "Jetta" },
  { id: 943, make: "VW", name: "Käfer" },
  { id: 940, make: "VW", name: "Karmann Ghia" },
  { id: 950, make: "VW", name: "LT" },
  { id: 951, make: "VW", name: "Lupo" },
  { id: 1722, make: "VW", name: "Multivan" },
  { id: 953, make: "VW", name: "New Beetle" },
  { id: 954, make: "VW", name: "Passat" },
  { id: 3242, make: "VW", name: "Passat Alltrack" },
  { id: 1578, make: "VW", name: "Passat CC" },
  { id: 3243, make: "VW", name: "Passat Variant" },
  { id: 955, make: "VW", name: "Phaeton" },
  { id: 956, make: "VW", name: "Polo" },
  { id: 942, make: "VW", name: "Scirocco" },
  { id: 957, make: "VW", name: "Sharan" },
  { id: 3245, make: "VW", name: "T-Cross" },
  { id: 3104, make: "VW", name: "T-Roc" },
  { id: 1683, make: "VW", name: "T1" },
  { id: 938, make: "VW", name: "T2" },
  { id: 939, make: "VW", name: "T3" },
  { id: 958, make: "VW", name: "T4" },
  { id: 959, make: "VW", name: "T5" },
  { id: 3244, make: "VW", name: "T5 Transporter" },
  { id: 2619, make: "VW", name: "T6" },
  { id: 3413, make: "VW", name: "Taigo" },
  { id: 1484, make: "VW", name: "Taro" },
  { id: 1007, make: "VW", name: "Tiguan" },
  { id: 3246, make: "VW", name: "Tiguan Allspace" },
  { id: 960, make: "VW", name: "Touareg" },
  { id: 961, make: "VW", name: "Touran" },
  { id: 1091, make: "VW", name: "Transporter" },
  { id: 1728, make: "VW", name: "Up" },
  { id: 941, make: "VW", name: "Vento" },
  { id: 2103, make: "VW", name: "XL1" },
  { id: 1081, make: "Wartburg", name: "311" },
  { id: 965, make: "Wartburg", name: "353" },
  { id: 966, make: "Wartburg", name: "andere" },
  { id: 968, make: "Wiesmann", name: "andere" },
  { id: 1486, make: "Wiesmann", name: "MF 3" },
  { id: 1628, make: "Wiesmann", name: "MF 4" },
  { id: 1629, make: "Wiesmann", name: "MF 5" },
  { id: 3571, make: "Xpeng", name: "andere" },
];

export interface PkwModel {
  id: number;
  make: string;
  name: string;
}

function normalizeText(value: string): string {
  return value
    .toLowerCase()
    .normalize("NFD")
    .replace(/\p{Diacritic}/gu, "")
    .replace(/\s+/g, " ")
    .trim();
}

export function listMakes(): string[] {
  const makes: string[] = [];
  for (const model of PKW_MODELS) {
    if (makes[makes.length - 1] !== model.make) makes.push(model.make);
  }
  return makes;
}

export function modelsByMake(make: string): PkwModel[] {
  const needle = normalizeText(make);
  if (!needle) return [];
  return PKW_MODELS.filter((model) => normalizeText(model.make) === needle);
}

export function findModel(id: number): PkwModel | undefined {
  if (!Number.isInteger(id) || id <= 0) return undefined;
  return PKW_MODELS.find((model) => model.id === id);
}

export function searchModels(query: string, limit?: number): PkwModel[] {
  const needle = normalizeText(query);
  if (!needle) return [];
  const cap = typeof limit === "number" && Number.isInteger(limit) && limit > 0 ? limit : 50;
  const results: PkwModel[] = [];
  for (const model of PKW_MODELS) {
    if (normalizeText(model.name).includes(needle) || normalizeText(model.make).includes(needle)) {
      results.push(model);
      if (results.length >= cap) break;
    }
  }
  return results;
}

